version: 0.0
os: linux
files:
  - source: ./README.md
    destination: /tmp/
  - source: ./index.php
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: ./scripts/before-installh.sh
  AfterInstall:
    - location: ./scripts/after-install.sh
